# Book settings
title: Scientific Computing with Python
author: Brad Nelson
#logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url : https://github.com/caam37830/book
  branch : master

html:
  use_repository_button: true
  use_issues_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
